-- EL ATELIER BOUTIQUE V4.1 - ejecutar una sola vez en Supabase > SQL Editor
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  ref text unique not null,
  name text not null,
  subtitle text default '',
  description text default '',
  price integer not null,
  category text not null default 'Ropa',
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  image text default '',
  active boolean not null default true,
  featured boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image text not null,
  storage_path text default '',
  color text default '',
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_products_active on public.products(active);
alter table public.products enable row level security;
alter table public.product_images enable row level security;
grant all on table public.products to service_role;
grant all on table public.product_images to service_role;
grant usage, select on all sequences in schema public to service_role;
insert into storage.buckets (id,name,public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;
